name: 'hello world docker action'
description: ' say hello'
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time we say hello.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
