name: Github Actions Demo
on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Builds:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " event that triggered was '${{github.event_name}}' ."
          echo "the name of the branch is '${{github.ref}}' and the repo is ."

      - uses: actions/checkout@v3.3.0

      - name: Listing files in the repo
          run:|
            echo "the repo ${{ github.repository }} contains the following files:"
            tree
    
